In [2]:
import numpy as np

In [40]:
a = np.array([
    [0.0, 5.0/11, 4.0/11, 2.0/11],
    [3.0/8, 0.0, 0.0, 5.0/8],
    [4.0/6., 0., 0., 2./6],
    [2.0/4., 1.0/4., 1./4., 0.0]
])
# a = np.array(a)

In [56]:
np.linalg.matrix_power(a, 1)

array([[0.        , 0.45454545, 0.36363636, 0.18181818],
       [0.375     , 0.        , 0.        , 0.625     ],
       [0.66666667, 0.        , 0.        , 0.33333333],
       [0.5       , 0.25      , 0.25      , 0.        ]])

In [57]:
np.linalg.matrix_power(a, 2)

array([[0.50378788, 0.04545455, 0.04545455, 0.40530303],
       [0.3125    , 0.32670455, 0.29261364, 0.06818182],
       [0.16666667, 0.38636364, 0.32575758, 0.12121212],
       [0.26041667, 0.22727273, 0.18181818, 0.33049242]])

In [61]:
np.linalg.matrix_power(a, 10)

array([[0.33726177, 0.21473614, 0.18439846, 0.26360362],
       [0.33557066, 0.21857159, 0.18796257, 0.25789518],
       [0.33470443, 0.22040633, 0.189656  , 0.25523324],
       [0.33559544, 0.21836778, 0.18776011, 0.25827667]])

In [62]:
np.linalg.matrix_power(a, 100)

array([[0.33598326, 0.21757322, 0.18702929, 0.25941423],
       [0.33598326, 0.21757322, 0.18702929, 0.25941423],
       [0.33598326, 0.21757322, 0.18702929, 0.25941423],
       [0.33598326, 0.21757322, 0.18702929, 0.25941423]])

In [13]:
A = np.array([
  [1, 2, -1],
  [1, 0, 1]
]).T
b= np.array([2, 1, 1]).reshape(-1, 1)

In [15]:
b.shape

(3, 1)

In [16]:
( A @ np.linalg.inv(A.T@A) @ A.T ).dot(b)

array([[2.],
       [1.],
       [1.]])

In [17]:
A.T@A

array([[6, 0],
       [0, 2]])

In [18]:
A @ np.linalg.inv(A.T@A) @ A.T 

array([[ 0.66666667,  0.33333333,  0.33333333],
       [ 0.33333333,  0.66666667, -0.33333333],
       [ 0.33333333, -0.33333333,  0.66666667]])

In [20]:
(np.linalg.inv(A.T@A) @ A.T).dot(b).shape

(2, 1)

In [26]:
pc = (1.0/25) * np.array([
    9, 12,
    12, 16
]).reshape(2,2)

a = np.array([
    3, 6, 6,
    4, 8, 8
]).reshape(2, 3)

pb = (1./81)*np.array([
    9, 18, 18,
    18, 36, 36,
    18, 36, 36
]).reshape(3, 3)



In [27]:
pc @ a @ pb

array([[3., 6., 6.],
       [4., 8., 8.]])

In [21]:
A =  np.array([
  [-1, 1, 0, 0],
  [-1, 0, 1, 0],
  [ 0, -1, 1, 0],
  [ 0, -1, 0, 1],
  [0, 0, -1, 1]
])

C = np.diag([2, 2, 3, 3, 3])

In [39]:
ZZ = A.T @ C @ A
ZZ

array([[ 4, -2, -2,  0],
       [-2,  8, -3, -3],
       [-2, -3,  8, -3],
       [ 0, -3, -3,  6]])

In [30]:
ZZ = np.delete(ZZ, 3, 0)
ZZ = np.delete(ZZ, 3, 1)
ZZ

array([[ 4, -2, -2],
       [-2,  8, -3],
       [-2, -3,  8]])

In [31]:
np.linalg.solve(ZZ, [1, 0, 0])

array([0.41666667, 0.16666667, 0.16666667])

In [35]:
-C @ A @ np.array([5./12, 1./6, 1./6, 0])

array([0.5, 0.5, 0. , 0.5, 0.5])

In [33]:
5./12, 1/6.

(0.4166666666666667, 0.16666666666666666)

In [37]:
!pip install scipy

  Using cached https://files.pythonhosted.org/packages/dd/6c/ccf7403d14f0ab0f20ce611696921f204f4ffce99a4fd383c892a6a7e9eb/scipy-1.2.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl


In [38]:
import scipy

# .linalg.lu

In [50]:
p, l, u = la.lu(ZZ)

In [51]:
u

array([[ 4.        , -2.        , -2.        ,  0.        ],
       [ 0.        ,  7.        , -4.        , -3.        ],
       [ 0.        ,  0.        ,  4.71428571, -4.71428571],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [60]:
A = np.array([
    [1, 1, 1, 1],
    [0, 1, 3, 4],
    [0, 1, 9, 16]
]).T

In [61]:
A.T @ A 

array([[  4,   8,  26],
       [  8,  26,  92],
       [ 26,  92, 338]])

In [62]:
A.T @ np.array([0, 8, 8, 20])

array([ 36, 112, 400])

In [56]:
np.array([0, 8, 8, 20]).reshape(-1, 1).shape

(4, 1)

In [2]:
A = np.array([
    [1, 1, 0],
    [1, 0, 1],
    [1, -1, 0],
    [1, 0, -1]
])

In [3]:
A.T @ A

array([[4, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [5]:
A.T @ np.array([0, 1, 3, 4]).reshape(-1, 1)

array([[ 8],
       [-3],
       [-3]])

In [7]:
A @ np.array([2, -3./2, -3./2])

array([0.5, 0.5, 3.5, 3.5])

In [17]:
a = np.array([1, -1, 0, 0])
b = np.array([0, 1, -1, 0])
c = np.array([0, 0, 1, -1])

In [11]:
B = b - (np.outer(a, a.T) @ b ) / (a.T.dot(a))

In [12]:
B

array([ 0.5,  0.5, -1. ,  0. ])

In [16]:
- (np.outer(a, a.T) @ b ) / (a.T.dot(a))

array([ 0.5, -0.5,  0. ,  0. ])

In [14]:
(a.T.dot(a))

2

In [18]:
c - (np.outer(a, a.T) @ c ) / (a.T.dot(a)) - (np.outer(B, B.T) @ c ) / (B.T.dot(B))

array([ 0.33333333,  0.33333333,  0.33333333, -1.        ])

In [24]:
A = np.eye(4) - np.diag([1,1,1], -1)

In [37]:
q,r = np.linalg.qr(A)
q

array([[-0.70710678, -0.40824829, -0.28867513,  0.5       ],
       [ 0.70710678, -0.40824829, -0.28867513,  0.5       ],
       [-0.        ,  0.81649658, -0.28867513,  0.5       ],
       [-0.        , -0.        ,  0.8660254 ,  0.5       ]])

In [41]:
print(q[:, 0] / 0.70710678)
print(q[:, 1] / 0.40824829)
print(q[:, 2] / 0.28867513)
print(q[:, 3] / 0.5)

[-1.  1. -0. -0.]
[-1. -1.  2. -0.]
[-1.00000002 -1.00000002 -1.00000002  3.00000005]
[1. 1. 1. 1.]


In [33]:
np.sqrt(q[:, 0].T.dot(q[:, 0]))

0.9999999999999998

In [46]:
from scipy.linalg import hilbert, lu

In [43]:
a = hilbert(5)

In [44]:
a

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [50]:
p, l, u = lu(a)

In [51]:
u

array([[ 1.00000000e+00,  5.00000000e-01,  3.33333333e-01,
         2.50000000e-01,  2.00000000e-01],
       [ 0.00000000e+00,  8.33333333e-02,  8.88888889e-02,
         8.33333333e-02,  7.61904762e-02],
       [ 0.00000000e+00,  0.00000000e+00, -5.55555556e-03,
        -8.33333333e-03, -9.52380952e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         7.14285714e-04,  1.45124717e-03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.13378685e-05]])

In [52]:
p

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]])